### ISSUE TITLE
Avoid genrating local files if possible

### ISSUE THREAD

**Issue by andantei** [tuneflow/tuneflow-plugin-demucs#1]
If deployed on server this will generate a large amount of files occupying disk space.
Plus disk io is much slower than memory.
Can we try to call it from python directly and read/write files using BytesIO?

**Comment by jackqjq** [comment]
This is a good point! I've updated the IO for the original track and separated the tracks. 

For the original track, Demucs requires to load from a file, so the raw bytes of the original track are written into a temporary file. The file will be deleted after converted to Tensor.

For output tracks, no file is written in the latest implementation.
